# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        id: step1
        with:
          fetch-depth: '0'
      
      # Creates a tag and bumps the version number up
      - name: Github Tag Bump
        id: step2
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: cpcolella
          INITIAL_VERSION: 2.0.0
          WITH_V: true
      
      - name: Create Release Folder
        id: step3
        run: rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' . ./release
        
      - name: Switch to Release Folder
        id: step4
        run: ls -la release
          
      - name: Zip Folder
        id: step5
        run: zip -r release_${{ steps.step2.outputs.new_tag }}.zip ./release -x ".git/*" ".github/*"
      
      #
      
      ## Publish to Chrome Store
      #- name: Chrome Extension upload & publish
      #  # You may pin to the exact commit or the version.
      #  uses: Passiverecords/chrome-extension-upload-action@1.4.1
      #  with:
      #    # Auth refresh token
      #    refresh-token: 
      #    # Extension application target id
      #    app-id: kalmlgjkibkjeepmlenkeljokfoijngl
      #    # Token client id
      #    client-id: 
      #    # Token client secret
      #    client-secret: 
      #    # Name of zipped target upload file
      #    file-name: release_${{ steps.step2.outputs.new_tag }}.zip
      #    # True Or False to publish after upload
      #    publish: 



